In [1]:
import pandas as pd

In [2]:
columns = [ "age", "workclass", "fnlwgt", "education", "education_num", "marital_status", "occupation", 
           "relationship", "race", "sex", "capital_gain", "capital_loss", "hours_per_week", "native_country", "income" ]

In [8]:
# Load the Adult dataset from the file "adult.data". 
# header=None → The dataset does not contain column names in the first row.
# so pandas should NOT treat the first row as a header.
# names=columns → Assign the predefined list of column names to the DataFrame. 
# na_values="?" → Convert any "?" in the dataset into proper missing values (NaN). 
# skipinitialspace=True → Remove any extra spaces after commas to clean the data.

df_train = pd.read_csv("adult.data", header=None, names=columns, na_values="?", skipinitialspace=True)

In [9]:
df_train.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [10]:
df_test = pd.read_csv("adult_test.csv", header=None, names=columns, na_values="?", skipinitialspace=True)

In [11]:
df_test.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K.

In [12]:
df_train["source"] = "train"
df_test["source"] = "test"

In [13]:
df_train_test = pd.concat([df_train, df_test], ignore_index=True)

In [14]:
df_train_test.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,train
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,train
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,train
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,train
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,train

In [23]:
df_train_test.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,source
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.,test
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.,test
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.,test
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,test
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.,test

In [24]:
df_train_test['income'].unique()

array(['<=50K', '>50K', '<=50K.', '>50K.'], dtype=object)

In [15]:
df_train_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       46043 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education_num   48842 non-null  int64
 5   marital_status  48842 non-null  object
 6   occupation      46033 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital_gain    48842 non-null  int64
 11  capital_loss    48842 non-null  int64
 12  hours_per_week  48842 non-null  int64
 13  native_country  47985 non-null  object
 14  income          48842 non-null  object
 15  source          48842 non-null  object
dtypes: int64(6), object(10)
memory usage: 6.0+ MB

In [16]:
df_train_test.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [17]:
df_train_test.isnull().sum()

age                  0
workclass         2799
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
income               0
source               0
dtype: int64

In [25]:
df_train_test['education'].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [26]:
df_train_test['income'].unique()

array(['<=50K', '>50K', '<=50K.', '>50K.'], dtype=object)

In [27]:
df_train_test[['education', 'income']].nunique()

education    16
income        4
dtype: int64

In [28]:
df_train_test['income'].value_counts()

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [29]:
df_train_test['income'] = df_train_test['income'].str.replace('.', '', regex=False).str.strip()

In [30]:
df_train_test['income'].value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

<span style="color: blue;"> 
Hypothesis Question 1:
Does education level affect the probability of earning more than 50K?

Variables:
Education → Categorical (16 levels)

Income Class → Binary categorical (>50K, ≤50K)

Hypotheses:
Null Hypothesis (H₀):
Education level does not affect the probability of earning >50K.  
Income distribution is the same across all education categories.

Alternative Hypothesis (H₁):
Higher education levels increase the probability of earning >50K.  
Income distribution differs across education categories. </span>

In [31]:
import scipy.stats as stats


# Create contingency table
table = pd.crosstab(df_train_test['education'], df_train_test['income'])

# Chi-square test
chi2, p, dof, expected = stats.chi2_contingency(table)

print("Chi-square:", chi2)
print("Degrees of freedom:", dof)
print("p-value:", p)

Chi-square: 6537.972961360963
Degrees of freedom: 15
p-value: 0.0

<span style="color: blue;">Interpretation: “The chi‑square test produced a p‑value smaller than the minimum representable value in Python (displayed as 0.0), indicating an extremely strong and statistically significant association between education level and income class.” </span>

<span style="color: blue;">Type I Error (False Positive) : reject H₀ even though it is actually true , We conclude that education affects income, even if in reality education has no real effect on income. </span>

<span style="color: blue;">Type II Error (False Negative): fail to reject H₀ even though H₁ is true, We conclude that education does not affect income, even though in reality higher education does increase the probability of earning >50K. </span>

<span style="color: blue;">Education is  associated with income </span>

In [32]:
df_train_test['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', nan, 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

<span style="color: blue;">Hypothesis Question 2  </span>
<span style="color: blue;">Does Workclass affect the probability of earning more than 50K?  </span>
<span style="color: blue;">Variables: Workclass → Categorical (9 levels, including missing)  </span>

<span style="color: blue;">Income Class → Binary categorical (>50K, ≤50K) </span>

<span style="color: blue;">Hypothesis: </span>
<span style="color: blue;">Null Hypothesis (H₀): </span>
<span style="color: blue;">Workclass does not affect income classification. </span>
<span style="color: blue;">i.e.Income distribution is the same across all workclass categories. </span>

<span style="color: blue;">Alternative Hypothesis (H₁): </span>
<span style="color: blue;">Workclass significantly affects income classification. </span>
<span style="color: blue;">i.e.Income distribution differs across workclass categories. </span>

In [33]:
# Contingency table
table = pd.crosstab(df_train_test['workclass'], df_train_test['income'])

# Chi-square test
chi2, p, dof, expected = stats.chi2_contingency(table)

print("Chi-square:", chi2)
print("Degrees of freedom:", dof)
print("p-value:", p)

Chi-square: 1238.990039222109
Degrees of freedom: 7
p-value: 2.6121798441462815e-263

<span style="color: blue;"> Interpretation:
p-value  is extremely small , i.e. We reject the null hypothesis (H₀). There is a highly significant association between workclass and income class.
Different workclass categories have different probabilities of earning >50K.  </Span>

<span style="color: blue;">People working in certain workclasses (e.g., Federal-gov, Self-emp-inc) are more likely to earn >50K, while others (e.g., Without-pay, Never-worked) are far less likely. </Span>

<span style="color: blue;">Type I Error (False Positive): Rejecting H₀ when H₀ is actually true, We  conclude that workclass affects income, even though in reality workclass has no effect on income, i.e.  workclass matters for income, but it actually doesn’t. </Span>

<span style="color: blue;">Type II Error (False Negative): Failing to reject H₀ when H₁ is actually true, We conclude that workclass does NOT affect income, even though in reality workclass DOES influence the probability of earning >50K, i.e. we miss a real effect — workclass actually matters, but you fail to detect it. </Span>